name: pdf_viewer_jk
description: A flutter plugin for viewing PDF files in mobile app (Android & iOS).
version: 2.0.0-nullsafety.2
repository: https://github.com/jawadsahil/pdf_viewer_jk
homepage: https://jawad.pro

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  async: ^2.5.0
  flutter_cache_manager: ^3.0.1
  path_provider: ^2.0.1
  numberpicker: ^2.0.1
  http: ^0.13.1
  path: ^1.8.0
  flutter_svg: ^0.21.0-nullsafety.0
  pool: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: pro.jawad.pdf_viewer_jk
        pluginClass: PdfViewerJkPlugin
      ios:
        pluginClass: PdfViewerJkPlugin
